### ISSUE TITLE
Null pointer exception from bad p:with-option 

### ISSUE THREAD

**Issue by alexmilowski** [ndw/xmlcalabash1#16]
If you mistakenly put in a bad p:with-option without a name attribute you get a null pointer exception:

java.lang.NullPointerException
    at com.xmlcalabash.model.Parser.readOption(Unknown Source)
    at com.xmlcalabash.model.Parser.readSignature(Unknown Source)
    at com.xmlcalabash.model.Parser.readStep(Unknown Source)
    at com.xmlcalabash.model.Parser.parseDeclareStepBody(Unknown Source)
    at com.xmlcalabash.model.Parser.usePipeline(Unknown Source)
    at com.xmlcalabash.model.Parser.loadPipeline(Unknown Source)
    at com.xmlcalabash.core.XProcRuntime._load(Unknown Source)
    at com.xmlcalabash.core.XProcRuntime.load(Unknown Source)

**Comment by ndw** [comment]
Fixed, I believe.
