### ISSUE TITLE
EntityResolver never used

### ISSUE THREAD

**Issue by alexmilowski** [ndw/xmlcalabash1#17]
I tried to hook in an entity resolver to use the internal client of the Restlet libraries I'm using but it looks like my resolver is never called:

INFO: Running load !1.4
com.xmlcalabash.core.XProcException: XProc error err:XD0011
    at com.xmlcalabash.core.XProcException.dynamicError(Unknown Source)
    at com.xmlcalabash.util.XProcURIResolver.parse(Unknown Source)
    at com.xmlcalabash.core.XProcRuntime.parse(Unknown Source)
    at com.xmlcalabash.library.Load.run(Unknown Source)
    at com.xmlcalabash.runtime.XAtomicStep.run(Unknown Source)
    at com.xmlcalabash.runtime.XPipeline.doRun(Unknown Source)
    at com.xmlcalabash.runtime.XPipeline.run(Unknown Source)
    at org.atomojo.server.xproc.XProcRestlet.handle(XProcRestlet.java:577)
    at org.restlet.routing.Filter.doHandle(Filter.java:156)
    at org.restlet.routing.Filter.handle(Filter.java:203)
    at org.restlet.routing.Router.doHandle(Router.java:428)
    at org.restlet.routing.Router.handle(Router.java:645)
    at org.atomojo.server.ConfiguredHost$1.handle(ConfiguredHost.java:61)
    at org.restlet.routing.Filter.doHandle(Filter.java:156)
    at org.restlet.routing.Filter.handle(Filter.java:203)
    at org.restlet.routing.Router.doHandle(Router.java:428)
    at org.restlet.routing.Router.handle(Router.java:645)
    at org.restlet.routing.Filter.doHandle(Filter.java:156)
    at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:151)
    at org.restlet.routing.Filter.handle(Filter.java:203)
    at org.restlet.routing.Filter.doHandle(Filter.java:156)
    at org.restlet.routing.Filter.handle(Filter.java:203)
    at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:208)
    at org.restlet.Component.handle(Component.java:389)
    at org.restlet.Server.handle(Server.java:513)
    at org.restlet.engine.ServerHelper.handle(ServerHelper.java:69)
    at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:149)
    at org.restlet.ext.jetty.JettyServerHelper$WrappedServer.handle(JettyServerHelper.java:167)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:589)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1048)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:601)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:214)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:411)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:535)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:529)
    at java.lang.Thread.run(Thread.java:680)
Caused by: net.sf.saxon.s9api.SaxonApiException: I/O error reported by XML parser processing riap://component/milowski.com/: unknown protocol: riap
    at net.sf.saxon.s9api.DocumentBuilder.build(DocumentBuilder.java:402)
    ... 36 more
Caused by: net.sf.saxon.trans.XPathException: I/O error reported by XML parser processing riap://component/milowski.com/: unknown protocol: riap
    at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:427)
    at net.sf.saxon.event.Sender.send(Sender.java:154)
    at net.sf.saxon.Configuration.buildDocument(Configuration.java:3321)
    at net.sf.saxon.s9api.DocumentBuilder.build(DocumentBuilder.java:399)
    ... 36 more
Caused by: java.net.MalformedURLException: unknown protocol: riap
    at java.net.URL.<init>(URL.java:574)
    at java.net.URL.<init>(URL.java:464)
    at java.net.URL.<init>(URL.java:413)
    at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
    at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
    at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
    at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
    at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:400)
    ... 39 more
Oct 26, 2011 12:13:34 PM com.xmlcalabash.util.DefaultXProcMessageListener error
SEVERE: err:XC0011:Could not load riap://component/milowski.com/ (file:/Users/alex/workspace/milowski/web/milowski.com/docs/test.xpl) dtd-validate=false
Oct 26, 2011 12:13:34 PM org.restlet.engine.application.StatusFilter doHandle
WARNING: Exception or error caught in status service
com.xmlcalabash.core.XProcException: Could not load riap://component/milowski.com/ (file:/Users/alex/workspace/milowski/web/milowski.com/docs/test.xpl) dtd-validate=false
    at com.xmlcalabash.core.XProcException.stepError(Unknown Source)
    at com.xmlcalabash.library.Load.run(Unknown Source)
    at com.xmlcalabash.runtime.XAtomicStep.run(Unknown Source)
    at com.xmlcalabash.runtime.XPipeline.doRun(Unknown Source)
    at com.xmlcalabash.runtime.XPipeline.run(Unknown Source)
    at org.atomojo.server.xproc.XProcRestlet.handle(XProcRestlet.java:577)
    at org.restlet.routing.Filter.doHandle(Filter.java:156)
    at org.restlet.routing.Filter.handle(Filter.java:203)
    at org.restlet.routing.Router.doHandle(Router.java:428)
    at org.restlet.routing.Router.handle(Router.java:645)
    at org.atomojo.server.ConfiguredHost$1.handle(ConfiguredHost.java:61)
    at org.restlet.routing.Filter.doHandle(Filter.java:156)
    at org.restlet.routing.Filter.handle(Filter.java:203)
    at org.restlet.routing.Router.doHandle(Router.java:428)
    at org.restlet.routing.Router.handle(Router.java:645)
    at org.restlet.routing.Filter.doHandle(Filter.java:156)
    at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:151)
    at org.restlet.routing.Filter.handle(Filter.java:203)
    at org.restlet.routing.Filter.doHandle(Filter.java:156)
    at org.restlet.routing.Filter.handle(Filter.java:203)
    at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:208)
    at org.restlet.Component.handle(Component.java:389)
    at org.restlet.Server.handle(Server.java:513)
    at org.restlet.engine.ServerHelper.handle(ServerHelper.java:69)
    at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:149)
    at org.restlet.ext.jetty.JettyServerHelper$WrappedServer.handle(JettyServerHelper.java:167)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:589)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1048)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:601)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:214)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:411)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:535)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:529)
    at java.lang.Thread.run(Thread.java:680)

**Comment by alexmilowski** [comment]
Here's a bit more information.  I had to implement the URIResolver as well in a similar way.  If the resource exists, everything works fine.  If the resource does not exist, my resolver returns null.  This causes the code at line #132 of XProcURIResolver.java to be executed where it constructs a SAXSource.  If the code had trusted my failure to resolve the URI, everything would have worked well and I would get a "file not found" (or whatever).

**Comment by alexmilowski** [comment]
Just a bit more:  Here's my pipeline:

<p:declare-step xmlns:p="http://www.w3.org/ns/xproc"
                xmlns:c="http://www.w3.org/ns/xproc-step"
                version="1.0"
                name="test">
<p:option name="base"/>
<p:option name="remaining"/>
<p:output port="result"/>

<p:load>
<p:with-option name='href' select="concat($base,$remaining)"/>
/p:load

/p:declare-step

If I throw an exception within the URIResolver instance, I can cause a better error message.  What I really want is for the p:load step to say "can't open this URI".

**Comment by alexmilowski** [comment]
By having the URIResolver/EntityResolver throw an XProcException as:

```
throw new XProcException(XProcConstants.dynamicError(11),"Cannot open resource "+resourceRef+", status "+response.getStatus());
```

I then get an error message that makes sense:

INFO: Response received: Not Found (404) - The server has not found anything matching the request URI
com.xmlcalabash.core.XProcException: Cannot open resource riap://component/milowski.com/foo, status Not Found (404) - The server has not found anything matching the request URI
    at org.atomojo.server.xproc.XProcCache$2.resolve(XProcCache.java:192)
    at com.xmlcalabash.util.XProcURIResolver.resolve(Unknown Source)
    at com.xmlcalabash.util.XProcURIResolver.parse(Unknown Source)
    at com.xmlcalabash.core.XProcRuntime.parse(Unknown Source)
    at com.xmlcalabash.library.Load.run(Unknown Source)
    at com.xmlcalabash.runtime.XAtomicStep.run(Unknown Source)
    at com.xmlcalabash.runtime.XPipeline.doRun(Unknown Source)
    at com.xmlcalabash.runtime.XPipeline.run(Unknown Source)

I still don't quite understand why I need to implement both a URIResolver and an EntityResolver.

**Comment by ndw** [comment]
Entity resolvers are used for external parsed entities and documents. URI resolvers are used for schemas, stylesheets, etc. Shame it's such a f'ed up API, but I don't think we can do anything about that now.

Is this issue now resolved?

**Comment by ndw** [comment]
Assuming so.
