### ISSUE TITLE
NullPointerException with non-primary output ports

### ISSUE THREAD

**Issue by gimsieke** [ndw/xmlcalabash1#174]
This is the third issue of #158. 

First, I use this pipeline 

``` xml
<p:declare-step xmlns:p="http://www.w3.org/ns/xproc" version="1.0">
  <p:input port="source"/>
  <p:output port="result" sequence="true" primary="false"/>
  <p:output port="result2" sequence="true" primary="false">
    <p:pipe step="id" port="result"/>
  </p:output>
  <p:identity name="id"/>
</p:declare-step>
```

in standalone Calabash. The input document.will be reproduced on output port result2.

After installing the pipeline in piperack (under the name 'my'), I’ll post a document to the source port and run the pipeline:

``` bash
curl -X POST  -H "Content-type: application/xml" -d @some.xml localhost:8089/pipelines/my/inputs/source
curl -X POST  localhost:8089/pipelines/my/run
```

There is no immediate result, which is no surprise since there is no primary output.
Inspecting the pipeline:

``` bash
curl localhost:8089/pipelines/my
```

``` xml
<pipeline xmlns="http://xmlcalabash.com/ns/piperack">
   <uri>http://localhost:8089/pipelines/my</uri>
   <expires>2014-08-24T22:26:25Z</expires>
   <has-run>true</has-run>
   <output documents="0">result</output>
   <output documents="1">result2</output>
</pipeline>
```

Retrieving result2’s document:

``` bash
curl localhost:8089/pipelines/my/outputs/result2
```

``` xml
<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Internal Server Error</p>
<p>The server encountered an unexpected condition which prevented it from fulfilling the request</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.5.1">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>
```

Looking at the stack trace:

``` text
java.lang.NullPointerException
        at com.xmlcalabash.model.Step.getOutput(Unknown Source)
        at com.xmlcalabash.model.CompoundStep.getOutput(Unknown Source)
        at com.xmlcalabash.runtime.XPipeline.getSerialization(Unknown Source)
        at com.xmlcalabash.piperack.BaseResource.getOutput(Unknown Source)
        at com.xmlcalabash.piperack.Output.get(Unknown Source)
        at org.restlet.resource.ServerResource.doHandle(ServerResource.java:618)
…
```

**Comment by gimsieke** [comment]
(Calabash 1.0.18 with Saxon HE 9.5.1.6)

**Comment by ndw** [comment]
Hmm. I can't reproduce that with the current dev branch.

**Comment by ndw** [comment]
Can you try this in 1.0.19 and see if it's fixed?

**Comment by gimsieke** [comment]
Yeah, it’s fixed now. 
I thought that it might be related to the more recent Saxon version that I used, but I managed to reproduce it with the original files that were shipped in http://xmlcalabash.com/download/calabash-1.0.18-95.zip
