### ISSUE TITLE
Strange base URI error with ant task

### ISSUE THREAD

**Issue by alexmilowski** [ndw/xmlcalabash1#175]
I get the following error from the ant task for something that previous work but I tweaked the pipeline.  The error doesn't make any sense.  If I run it outside of ant, it works fine.

/Users/alex/workspace/github/ischool-iolab/data/bug/build.xml:23: com.xmlcalabash.core.XProcException: Expression could not be evaluated: h:head/h:title
    at com.xmlcalabash.core.XProcException.dynamicError(Unknown Source)
    at com.xmlcalabash.util.ProcessMatch.match(Unknown Source)
    at com.xmlcalabash.runtime.XViewport.run(Unknown Source)
    at com.xmlcalabash.runtime.XPipeline.doRun(Unknown Source)
    at com.xmlcalabash.runtime.XPipeline.run(Unknown Source)
    at com.xmlcalabash.drivers.Main.run(Unknown Source)
    at com.xmlcalabash.drivers.CalabashTask.process(Unknown Source)
    at com.xmlcalabash.drivers.CalabashTask.execute(Unknown Source)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
    at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
    at org.apache.tools.ant.Main.runBuild(Main.java:851)
    at org.apache.tools.ant.Main.startAnt(Main.java:235)
    at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
    at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Caused by: java.lang.IllegalArgumentException: Supplied base URI must be absolute
    at net.sf.saxon.s9api.XPathCompiler.setBaseURI(XPathCompiler.java:208)
    at com.xmlcalabash.io.Select.readSource(Unknown Source)
    at com.xmlcalabash.io.Select.moreDocuments(Unknown Source)
    at com.xmlcalabash.library.Filter.run(Unknown Source)
    at com.xmlcalabash.runtime.XAtomicStep.run(Unknown Source)
    at com.xmlcalabash.runtime.XViewport.processStartElement(Unknown Source)
    at com.xmlcalabash.util.ProcessMatch.traverse(Unknown Source)
    at com.xmlcalabash.util.ProcessMatch.traverse(Unknown Source)
    at com.xmlcalabash.util.ProcessMatch.traverse(Unknown Source)
    at com.xmlcalabash.util.ProcessMatch.traverse(Unknown Source)
    ... 48 more

**Comment by alexmilowski** [comment]
Test files at https://gist.github.com/639763f3fe33869d6a2d.git

**Comment by ndw** [comment]
I believe this is fixed in XML Calabash 1.0.19, released today.
