### ISSUE TITLE
pulling down xmlcalabash as gradle dep and attempt to use results in security signing error with saxon

### ISSUE THREAD

**Issue by xquery** [ndw/xmlcalabash1#203]
dependencies get downloaded all fine, though when I try to execute (via com.xmlcalabash.drivers.Main)
I get following error complaining about non matching signer info...

```
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
    ... 44 more
Caused by: java.lang.SecurityException: class "net.sf.saxon.om.StructuredQName"'s signer information does not match signer information of other classes in the same package
    at net.sf.saxon.s9api.QName.<init>(QName.java:45)
    at net.sf.saxon.s9api.QName.<clinit>(QName.java:332)
    ... 54 more
```

**Comment by ndw** [comment]
Hmm. Can you provide a build.gradle to reproduce this? I have no trouble building https://github.com/ndw/xmlcalabash1-docs with gradle and it pulls down the latest maven release.

**Comment by xquery** [comment]
I think the appropriate test would be if you delete your gradle cache and pull down deps freshly.

**Comment by ndw** [comment]
I blew away ./.gradle and ~/.gradle and re-ran 'gradle clean dist' in the XML Calabash docs project and it built without any problems.

Does that one work for you?

**Comment by xquery** [comment]
hmmm, must be a local problem .. will continue investigating.

**Comment by xquery** [comment]
this morning, reran and it works .... ummmm, apologies for the noise
