### ISSUE TITLE
xsl-formatter href failure

### ISSUE THREAD

**Issue by greut** [ndw/xmlcalabash1#244]
Hi, I'm trying to get the a PDF file being written from a xsl-fo document.

``` xml
<p:xsl-formatter name="pdf" content-type="application/pdf">
         <p:with-option name="href" select="$pdf"/>
```
#### `document.pdf` or `file:document.pdf` or `file:///tmp/document.pdf`

```
Caused by: java.net.UnknownServiceException: protocol doesn't support output
        at java.net.URLConnection.getOutputStream(URLConnection.java:843)
        at com.xmlcalabash.io.URLDataStore.writeEntry(URLDataStore.java:56)
        at com.xmlcalabash.io.HttpClientDataStore.writeEntry(HttpClientDataStore.java:144)
        at com.xmlcalabash.library.XSLFormatter.run(XSLFormatter.java:118)
```
#### `file://document.pdf`

```
Caused by: java.net.UnknownHostException: document.pdf
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at sun.net.ftp.impl.FtpClient.doConnect(FtpClient.java:957)
        at sun.net.ftp.impl.FtpClient.tryConnect(FtpClient.java:917)
        at sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1012)
        at sun.net.ftp.impl.FtpClient.connect(FtpClient.java:998)
        at sun.net.www.protocol.ftp.FtpURLConnection.connect(FtpURLConnection.java:294)
        at sun.net.www.protocol.ftp.FtpURLConnection.getOutputStream(FtpURLConnection.java:507)
        at com.xmlcalabash.io.URLDataStore.writeEntry(URLDataStore.java:56)
        at com.xmlcalabash.io.HttpClientDataStore.writeEntry(HttpClientDataStore.java:144)
        at com.xmlcalabash.library.XSLFormatter.run(XSLFormatter.java:118)
```

What am I missing to avoid using the `HttpClientDataStore` and get the `FileDataStore` instead?

Best.

**Comment by greut** [comment]
This works.

```gradle
    option('pdf', 'ftp://localhost/output/document.pdf')
```

**Comment by ndw** [comment]
That is very odd. Let me try a test.

**Comment by ndw** [comment]
I can't reproduce this problem. What version of XML Calabash are you running? What version of Java? What FO backend are you using?

This works for me with FOP:

```xml
<p:declare-step xmlns:p="http://www.w3.org/ns/xproc"
                xmlns:xi="http://www.w3.org/2001/XInclude"
                xmlns:c="http://www.w3.org/ns/xproc-step"
                version="1.0">
<p:input port="parameters" kind="parameter"/>

<p:xsl-formatter name="xsl-fo"
		 href="/tmp/out.pdf" content-type="application/pdf">
  <p:input port="source">
    <p:document href="http://tests.xproc.org/tests/doc/envelope.fo"/>
  </p:input>
</p:xsl-formatter>

</p:declare-step>
```

**Comment by greut** [comment]
@ndw Thanks for your time! Much appreciated.

It finally worked after removing the `safeMode` option. Crazy enough.

```diff
diff --git a/build.gradle b/build.gradle
index 40b09f1..c1ed3cb 100644
--- a/build.gradle
+++ b/build.gradle
@@ -21,7 +21,6 @@ defaultTasks 'run'
 task run(type: com.xmlcalabash.XMLCalabashTask) {
   pipeline = file("pipe.xpl")
   debugPipeline = true
-  safeMode = true
```

**Comment by ndw** [comment]
Ah. Ok. That's working as designed, then. Safe mode is supposed to prevent a pipeline from writing to the local filesystem.

**Comment by greut** [comment]
okay... too few [rtfm](http://xmlcalabash.com/docs/reference/cfg.safe-mode.html) from my side. The name sounded good though.
