### ISSUE TITLE
cz:unzip throws 'no class in configuration'

### ISSUE THREAD

**Issue by xquery** [ndw/xmlcalabash1#25]
using xmlcalabash-0.9.43.94

getting the following when a pipeline tries to utilize the cx:unzip step

Jan 6, 2012 9:15:56 PM com.xmlcalabash.drivers.Main error
SEVERE: Pipeline failed: java.lang.UnsupportedOperationException:
Misconfigured. No 'class' in configuration for cx:unzip
java.lang.UnsupportedOperationException: Misconfigured. No 'class' in configuration for cx:unzip
    at com.xmlcalabash.core.XProcConfiguration.newStep(XProcConfiguration.java:412)
    at com.xmlcalabash.runtime.XAtomicStep.run(XAtomicStep.java:277)
    at com.xmlcalabash.runtime.XCompoundStep.run(XCompoundStep.java:256)
    at com.xmlcalabash.runtime.XChoose.run(XChoose.java:132)
    at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:236)
    at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:136)
    at com.xmlcalabash.drivers.Main.run(Main.java:320)
    at com.xmlcalabash.drivers.Main.main(Main.java:81)

**Comment by ndw** [comment]
My bad. Somehow the configuration for unzip got deleted.
