### ISSUE TITLE
[Question] Feature.PREFER_JAXP_PARSER is not in Saxon 11.3

### ISSUE THREAD

**Issue by aanno** [ndw/xmlcalabash1#334]
Hello, 

`XProcConfiguration` contains a line

```java
        bFeatureMap.put("http://saxon.sf.net/feature/preferJaxpParser", Feature.PREFER_JAXP_PARSER);
```

However, Feature.PREFER_JAXP_PARSER is not in Saxon 11.3. Hence

```bash
[main] WARN DbXslt20Ng - xslt20 format: html output: /mnt/home/tpasch/scm/aanno/db-toolchain/./asciidoc-writers-guide.html5 xpl: /mnt/home/tpasch/scm/aanno/db-toolchain/src/main/resources/docbook-xsl20/db2html-db-toolchain.xpl
Exception in thread "main" java.lang.NoSuchFieldError: PREFER_JAXP_PARSER
        at xmlcalabash@1.3.2-100/com.xmlcalabash.core.XProcConfiguration.<clinit>(XProcConfiguration.java:168)
        at com.github.aanno.dbtoolchain@1.0.0-SNAPSHOT/com.github.aanno.dbtoolchain.org.docbook.XSLT20.newDefaultXProcRuntime(XSLT20.java:254)
```

What to do about it?

**Comment by ndw** [comment]
I think there are other changes that will be necessary for Saxon 11. I have been working on it, but my time is divided in a lot of different directions. I'll see if I can get it out this weekend.

**Comment by aanno** [comment]
Nevermind. Just wondered. I could stick to a saxon 10.x for a while...
