### ISSUE TITLE
'docs' fails with XPointer/XInclude error

### ISSUE THREAD

**Issue by MenteaXML** [ndw/xmlcalabash1#47]
Getting this error when running `distrib` target:

```
docs:
     [java] 16-May-2012 17:21:27 com.xmlcalabash.util.DefaultXProcMessageListener error
     [java] SEVERE: err:XC0001:XPointer is not allowed on XInclude when parse='text'
     [java] 16-May-2012 17:21:27 com.xmlcalabash.drivers.Main error
     [java] SEVERE: Unknown error
     [java] com.xmlcalabash.core.XProcException: XPointer is not allowed on XInclude when parse='text'
     [java]     at com.xmlcalabash.core.XProcException.stepError(XProcException.java:184)
     [java]     at com.xmlcalabash.library.XInclude.processStartElement(XInclude.java:162)
     [java]     at com.xmlcalabash.util.ProcessMatch.traverse(ProcessMatch.java:201)
     [java]     at com.xmlcalabash.util.ProcessMatch.traverse(ProcessMatch.java:235)
     [java]     at com.xmlcalabash.util.ProcessMatch.traverse(ProcessMatch.java:235)
     [java]     at com.xmlcalabash.util.ProcessMatch.traverse(ProcessMatch.java:235)
     [java]     at com.xmlcalabash.util.ProcessMatch.traverse(ProcessMatch.java:235)
     [java]     at com.xmlcalabash.util.ProcessMatch.match(ProcessMatch.java:97)
     [java]     at com.xmlcalabash.library.XInclude.expandXIncludes(XInclude.java:129)
     [java]     at com.xmlcalabash.library.XInclude.processStartElement(XInclude.java:220)
     [java]     at com.xmlcalabash.util.ProcessMatch.traverse(ProcessMatch.java:201)
     [java]     at com.xmlcalabash.util.ProcessMatch.traverse(ProcessMatch.java:235)
     [java]     at com.xmlcalabash.util.ProcessMatch.traverse(ProcessMatch.java:190)
     [java]     at com.xmlcalabash.util.ProcessMatch.match(ProcessMatch.java:97)
     [java]     at com.xmlcalabash.library.XInclude.expandXIncludes(XInclude.java:129)
     [java]     at com.xmlcalabash.library.XInclude.run(XInclude.java:120)
     [java]     at com.xmlcalabash.runtime.XAtomicStep.run(XAtomicStep.java:366)
     [java]     at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:236)
     [java]     at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:136)
     [java]     at com.xmlcalabash.drivers.Main.run(Main.java:320)
     [java]     at com.xmlcalabash.drivers.Main.main(Main.java:76)
```

**Comment by ndw** [comment]
Fixed, I believe.

**Comment by MenteaXML** [comment]
After looking in the build file, I'd already given up trying to run it anyway because of the hardcoded paths to things I don't have.  When I document the Ant task, it will be in valid DocBook 5 but without any promises about how it will format.

**Comment by ndw** [comment]
Sigh. I'll try to clean things up so that it runs without anything hardcoded. Just laziness on my part.
